### ISSUE TITLE
Support cuTENSOR 1.3.0

### ISSUE THREAD

**Issue by leofang** [conda-forge/cutensor-feedstock#11]
TODO:
- [x] Patch repodata to pin 1.2 series exactly, as 1.3+ is binary incompatible (done in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/141):
> Not binary compatible with previous versions, due to added int64 stride support.

https://docs.nvidia.com/cuda/cutensor/release_notes.html#cutensor-v1-3-0
- [ ] Pin stricter globally:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d3f8b37654cc25d9b141ffcbf36025d6b9cb223a/recipe/conda_build_config.yaml#L356-L357
- [x] Get a machine-readable link for Windows (@mnicely)

**Comment by mnicely** [comment]
@leofang I got the windows machine downloadable issue fixed. 
Can we bump this to version 1.3.1?

**Comment by leofang** [comment]
Thanks, Matt! I'll try to work on this in the next few days.
