### ISSUE TITLE
ppc64le library is broken

### ISSUE THREAD

**Issue by leofang** [conda-forge/cutensor-feedstock#16]
See https://github.com/conda-forge/cudnn-feedstock/issues/31#issuecomment-896243126. This has the very same cause as its cuDNN counterpart (https://github.com/conda-forge/cudnn-feedstock/issues/31): patchelf didn't handle the page size correctly. Apparently this is a known issue on ppc64le/aarch64:
- https://github.com/conda-forge/cudatoolkit-feedstock/pull/4#issuecomment-709453563
- https://github.com/JuliaLang/julia/pull/33745 
- https://github.com/numpy/numpy/issues/16677#issuecomment-648961042

Many thanks to @njzjz for reporting and testing for us!

**Comment by leofang** [comment]
Hi @njzjz Could you do me one more favor? Let's get the CUDA context initialized before importing `cutensor`:
```
python -c "import cupy as cp; a = cp.empty(10); from cupy import cutensor;"
```

**Comment by njzjz** [comment]
same error:
```
(/scratch/07349/njzjz/my_test_env3) login2.longhorn(1010)$ python -c "import cupy as cp; a = cp.empty(10); from cupy import cutensor;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cupy/cutensor.pyx", line 1, in init cupy.cutensor
ImportError: /scratch/07349/njzjz/my_test_env3/lib/python3.9/site-packages/cupy_backends/cuda/libs/../../../../../libcutensor.so.1: undefined symbol: cudaMemsetAsync
```

**Comment by leofang** [comment]
OK...Thank you @njzjz. I'll ask cuTENSOR people next week.

**Comment by leofang** [comment]
Hi @njzjz if you reinstall `cutensor` the test should now pass. Could you kindly test it for me one more time? 🙂

**Comment by njzjz** [comment]
@leofang Yes, it works!

**Comment by leofang** [comment]
Great, many thanks @njzjz!
