### ISSUE TITLE
Package description incorrect

### ISSUE THREAD

**Issue by leofang** [conda-forge/cutensor-feedstock#4]
@jakirkham Looks like I would need you or someone else to help manually copy the correct info over...😥
![image](https://user-images.githubusercontent.com/5534781/105795584-142ba780-5f5b-11eb-9ff9-7a31681ec9c6.png)

**Comment by jakirkham** [comment]
How does this look?

<img width="1792" alt="Screen Shot 2021-01-26 at 10 53 48 AM" src="https://user-images.githubusercontent.com/3019665/105890930-d5323c00-5fc4-11eb-87a8-478b7835a8d6.png">

cc @kkraus14

**Comment by kkraus14** [comment]
LGTM!

**Comment by leofang** [comment]
Awesome, thanks @jakirkham! I hope they'll fix this soon so we won't have to do this anymore 🙂
