### ISSUE TITLE
aarch64 binaries require glibc 2.27+

### ISSUE THREAD

**Issue by leofang** [conda-forge/cutensor-feedstock#46]
xref: https://github.com/conda-forge/cutensor-feedstock/blob/180a5cbedc913850e5cb1a4ba1c095a7002d9118/recipe/run_test.sh#L10-L14

This wasn't detected until now, because of the same reason discovered elsewhere: https://github.com/conda-forge/cuquantum-feedstock/pull/47#issuecomment-1700751650. Now that we switch to the non-CUDA image for CUDA 12 builds, it gets exposed.

We should add `run_constrained: __glibc >= 2.27` when the infra is ready.

**Comment by leofang** [comment]
It seems cuTENSOR 2.0 for ppc64le needs at least glibc 2.22 (https://github.com/conda-forge/cutensor-feedstock/pull/50#issuecomment-1821342814).

**Comment by jakirkham** [comment]
Cross-linking to CUDA Toolkit CentOS 7 deprecation issue ( https://github.com/conda-forge/cuda-feedstock/issues/28 ), which this depends on

**Comment by carterbox** [comment]
Closed by #62
