### ISSUE TITLE
Drop `conda_build_config.yaml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cutensor-feedstock#55]
The `conda_build_config.yaml` was added here to handle ARM SBSA:

https://github.com/conda-forge/cutensor-feedstock/blob/ee4d11f6a02afe7a06b25b917bcbce82b9b5713e/recipe/conda_build_config.yaml#L1-L2

However the logic here has been [included in `conda-forge-pinning`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/63a38e99a6a0bc2ff4bd4b0a9891ff89ae284843/recipe/conda_build_config.yaml#L52-L53 )

So the logic can be dropped. As this is the only thing in `conda_build_config.yaml`, the file itself can be dropped completely

Hopefully simplifies things here going forward

**Comment by carterbox** [comment]
Why is `arm_variant_type` pinned channel wide? I seems to me that this should be something like the mpi metapackage where it is recipe specific? Don't feedstocks which build for both `sbsa` and `tegra` still need to overwrite this pinning?
